<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Clinica.Modulo.Faturamento/Clinica.Modulo.Faturamento.csproj" /><ProjectReference Include="../../src/Clinica.Modulo.Gerente/Clinica.Modulo.Gerente.csproj" /><ProjectReference Include="../../src/Clinica.Modulo.Recepcao/Clinica.Modulo.Recepcao.csproj" /></ItemGroup></Project>
