using static Clinica.Desktop.Shell.Web.PaginasWebController;
namespace Clinica.Desktop.Shell.Web;
public sealed class AjudaWebViewModel {
public string Resposta0 => "O traço quer dizer “não medido”: a métrica não teve base de cálculo naquele período — um dia sem horário concluído não tem taxa de falta, um mês sem faturamento não tem margem. 0% e “não medido” são coisas diferentes, e o sistema nunca troca um pelo outro; nas planilhas exportadas o traço sai igual, para a média do Excel não ser calculada sobre um número que não existe.";
public string Resposta1 => "O menu superior só mostra o que o seu acesso alcança: item que exige uma permissão que o seu usuário não tem simplesmente não aparece. Quem concede é a direção, na tela de Acessos — cada permissão pode ser liberada a uma pessoa específica, num clique, sem mudar o perfil dos colegas. Cada aplicativo também carrega só os módulos do seu posto: uma tela pode existir no Gerente Geral e não existir no aplicativo da Recepção.";
public string Resposta2 => "Na Agenda, use “Fechar agenda…”: o período fica bloqueado e os vãos deixam de ser oferecidos. Fechar não desmarca ninguém — quem já estava marcado dentro do período é devolvido para a recepção remarcar, porque sessão que some sem ninguém avisar o paciente é pior do que o choque de horário. O encaixe continua furando o bloqueio de propósito.";
public string Resposta3 => "Dar baixa — registrar que a guia foi efetivada no sistema do convênio — é ato do aplicativo de Faturamento; no Gerente Geral, a fila de Pendências também baixa. O número da guia é conferido contra o formato daquele convênio enquanto você digita (a Unimed só numera com dígitos, por exemplo), para o “O” no lugar do zero não passar e só aparecer no retorno da operadora, semanas depois.";
public string Resposta4 => "Registre a glosa no aplicativo de Faturamento (Controle de glosas), que monta o recurso e mostra o que mais glosa nesta clínica e como evitar. Cada glosa ganha uma data-limite de recurso vigiada no painel — passado o prazo, não é mais pendência, é prejuízo consumado. A leitura consolidada fica no Gerente Geral.";
public string Resposta5 => "As telas com o botão “Exportar” geram planilha CSV pronta para o Excel em português — ela abre com as colunas separadas e a acentuação certa. Os lotes TISS exportam XML no padrão ANS. Métrica sem base de cálculo sai como “—” na planilha, igual à tela.";
public string Resposta6 => "A recusa aparece escrita perto do botão que a causou, e sempre diz o motivo — botão que fica apagado também está dizendo que falta algo (permissão, paciente escolhido, campo obrigatório). Algumas ações pedem justificativa escrita por desenho: divergência no fechamento de caixa, perda de estoque, cancelamento de registro clínico. A justificativa fica guardada e aparece na trilha de auditoria — é ela que responde “quem fez isso, e por quê” depois.";
public string Resposta7 => "Falha nunca aparece como sucesso: quando uma leitura não pôde ser feita, a tela mostra “não foi possível verificar” em vez de zeros — um painel dizendo “nenhuma pendência” por causa de uma consulta quebrada seria pior do que um painel que avisa. Se aparecer esse estado, use Atualizar; persistindo, é problema de conexão ou defeito, nunca “não há nada”.\n\nPara relatar um problema técnico: anote a hora em que aconteceu e o que estava sendo feito. O sistema guarda um registro técnico em arquivos mensais (erros-ano-mês.txt) na pasta “logs”, ao lado de onde o aplicativo está instalado — e, quando não pode gravar ali, em ClinicaSemDor\\logs dentro da pasta do usuário (AppData). É esse arquivo que diz a causa exata, e é o que o suporte vai pedir.";
}
public static partial class RegistroCompartilhadoWeb {
public static IEnumerable<Pagina> Paginas(){yield return new("ajuda","Ajuda e suporte",typeof(AjudaWebViewModel),[],[],[
new Secao("duvida-0","Por que um número aparece como “—” em vez de zero?",null,[new Campo("Resposta0","","leitura")],[],[],[]),
new Secao("duvida-1","Não encontro um item de menu que deveria existir",null,[new Campo("Resposta1","","leitura")],[],[],[]),
new Secao("duvida-2","Como fechar a agenda para férias ou feriado?",null,[new Campo("Resposta2","","leitura")],[],[],[]),
new Secao("duvida-3","Como dar baixa em uma guia de convênio?",null,[new Campo("Resposta3","","leitura")],[],[],[]),
new Secao("duvida-4","O convênio glosou uma guia — e agora?",null,[new Campo("Resposta4","","leitura")],[],[],[]),
new Secao("duvida-5","Como exportar dados para o Excel?",null,[new Campo("Resposta5","","leitura")],[],[],[]),
new Secao("duvida-6","O sistema recusou uma ação. Onde vejo o porquê?",null,[new Campo("Resposta6","","leitura")],[],[],[]),
new Secao("duvida-7","Quando algo der errado",null,[new Campo("Resposta7","","leitura")],[],[],[]),
],[],Subtitulo:null,Fabrica:_=>new AjudaWebViewModel());}}