using System.Linq;
using P=Clinica.Desktop.Shell.Web.PaginasWebController;
namespace Clinica.Clinico.Web;
public static partial class ClinicoWebRegistro {
    private static P.Secao SalaInfusaoCompleta() => new("SalaInfusaoCompleta", "Sala Infusao", null,
        [new("CodigoBusca", "Codigo Busca", "texto"), new("IncluirEncerradas", "Mostrar encerradas", "booleano")],
        ["Resumo|Resumo", "ResumoValidacoes|Resumo Validacoes"],
        [
            new("Validacoes", "Validacoes", ["Validacoes"], vm => ((Clinica.Desktop.Shell.Componentes.SalaInfusaoViewModel)vm).Validacoes.Cast<object>(), [new("Paciente", "Paciente"), new("Numero", "Numero")], [], [new("Abrir", "Avaliar e assinar")]),
            new("Folhas", "Folhas", ["Folhas"], vm => ((Clinica.Desktop.Shell.Componentes.SalaInfusaoViewModel)vm).Folhas.Cast<object>(), [new("Hora", "Hora"), new("Paciente", "Paciente"), new("Numero", "Numero"), new("Prescritor", "Prescritor"), new("Itens", "Itens"), new("Progresso", "Progresso"), new("Dia", "Dia")], [], [new("Imprimir", "Imprimir"), new("Anotar", "Anotar", Guarda: "vm:PodeRegistrarEnfermagem"), new("Abrir", "Abrir folha", Guarda: "vm:PodeChecar")]),
        ], [new("AbrirPorCodigo", "Abrir pelo código"), new("Carregar", "Atualizar"), new("RegistrarInfusao", "Registrar infusão com orientação externa")]);

    private static P.Secao EnfermagemCompleta() => new("EnfermagemCompleta", "Enfermagem", null,
        [new("Seletor.Termo", "Termo", "texto"), new("Escolhido", "Escolhido", "selecao", Opcoes: "Pacientes", RotuloOpcao: "Nome"), new("Plano.Hora", "Hora", "texto", Guarda: "Plano.PodeChecar"), new("Passagem.DataDoAtendimento", "Data Do Atendimento", "data"), new("Passagem.Hora", "Hora", "texto"), new("Passagem.Sistolica", "Sistolica", "texto"), new("Passagem.Diastolica", "Diastolica", "texto"), new("Passagem.Cardiaca", "Cardiaca", "texto"), new("Passagem.Respiratoria", "Respiratoria", "texto"), new("Passagem.Saturacao", "Saturacao", "texto"), new("Passagem.ConsultaCompleta", "Consulta Completa", "booleano"), new("Passagem.Intercorrencia", "Intercorrencia", "booleano"), new("Passagem.AlergiaObservada", "Alergia Observada", "texto"), new("Passagem.Texto", "Texto", "textarea")],
        ["ResumoDaLista|Resumo Da Lista", "Seletor.Erro|Erro", "Paciente|Paciente", "Contexto|Contexto", "Alerta|Alerta", "Cronometro|Cronometro", "Plano.Resumo|Resumo", "Passagem.Contexto|Contexto", "Passagem.EtapasEmFalta|Etapas Em Falta", "LinhaDoTempo.Resumo|Resumo"],
        [
            new("Pacientes", "Pacientes", ["Pacientes"], vm => ((Clinica.Desktop.Shell.Componentes.EnfermagemViewModel)vm).Pacientes.Cast<object>(), [new("Nome", "Nome")], [], [new("Atender", "Atender")]),
            new("Plano.Cuidados", "Cuidados", ["Plano.Cuidados"], vm => ((Clinica.Desktop.Shell.Componentes.EnfermagemViewModel)vm).Plano.Cuidados.Cast<object>(), [new("Redacao", "Redacao"), new("Selo", "Selo"), new("Registro", "Registro")], [], [new("Plano.MarcarFeito", "Feito", Guarda: "vm:Plano.PodeChecar"), new("Plano.MarcarNaoFeito", "Não feito", Guarda: "vm:Plano.PodeChecar")]),
            new("Passagem.Registros", "Registros", ["Passagem.Registros"], vm => ((Clinica.Desktop.Shell.Componentes.EnfermagemViewModel)vm).Passagem?.Registros.Cast<object>() ?? [], [new("Hora", "Hora"), new("Data", "Data"), new("Texto", "Texto"), new("SinaisVitais", "Sinais Vitais"), new("Marca", "Marca"), new("Assinatura", "Assinatura")], [], [new("Passagem.VincularSessao", "Vincular à sessão", Guarda: "vm:Passagem.PodeRegistrar"), new("Passagem.Corrigir", "Corrigir", Guarda: "vm:Passagem.PodeRegistrar"), new("Passagem.CancelarRegistro", "Cancelar", Guarda: "vm:Passagem.PodeRegistrar")]),
            new("LinhaDoTempo.Chips", "Chips", ["LinhaDoTempo.Chips"], vm => ((Clinica.Desktop.Shell.Componentes.EnfermagemViewModel)vm).LinhaDoTempo.Chips.Cast<object>(), [new("Rotulo", "Rotulo"), new("Texto", "Texto"), new("Quantidade", "Quantidade")], [], [new("LinhaDoTempo.Escolher", "Escolher")]),
            new("LinhaDoTempo.Itens", "Itens", ["LinhaDoTempo.Itens"], vm => ((Clinica.Desktop.Shell.Componentes.EnfermagemViewModel)vm).LinhaDoTempo.Itens.Cast<object>(), [new("Data", "Data"), new("HoraTexto", "Hora Texto"), new("Rotulo", "Rotulo"), new("Titulo", "Titulo"), new("Detalhe", "Detalhe"), new("Marca", "Marca"), new("Autor", "Autor")], [], [new("LinhaDoTempo.Ver", "Ver", Guarda: "vm:LinhaDoTempo.TemAcaoVer"), new("LinhaDoTempo.Abrir", "Abrir", Guarda: "vm:LinhaDoTempo.TemAcaoAbrir"), new("LinhaDoTempo.Cancelar", "Cancelar…", Guarda: "vm:LinhaDoTempo.TemAcaoCancelar")]),
        ], [new("Hoje", "Na clínica hoje"), new("Todos", "Todos os pacientes"), new("Voltar", "Voltar"), new("AbrirFolha", "Abrir Folha", Guarda: "PodeAbrirFolha"), new("ColherTermo", "Colher Termo", Guarda: "PodeColherTermo"), new("Passagem.CancelarCorrecao", "Cancelar correção"), new("ImprimirFicha", "Imprimir a passagem", Guarda: "PodeVerProntuario"), new("Passagem.Registrar", "Registrar", Guarda: "PodeRegistrar"),new("Passagem.AbrirConsultaWeb","Consulta completa de enfermagem",Guarda:"PodeRegistrar")]);
}
