// <auto-generated />
using System;
using Clinica.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinica.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    partial class ClinicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinica.Domain.Entities.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ChegadaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("Encaixe")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("InicioAtendimentoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<int?>("SalaId")
                        .HasColumnType("integer");

                    b.Property<string>("EspecialidadeConsulta")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EspecialidadeConsultaCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ModalidadeCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ModalidadePrevista")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("DataHora");

                    b.HasIndex("PacienteId");

                    b.HasIndex("SalaId");

                    b.HasIndex("ProfissionalId", "DataHora");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Profissional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cor")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int?>("DuracaoPadraoMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EspecialidadeCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NomeCurto")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("RegistroConselho")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ListaEspera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly?>("DisponivelAte")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DisponivelDe")
                        .HasColumnType("date");

                    b.Property<string>("ModalidadeCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Prioritario")
                        .HasColumnType("boolean");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("Status");

                    b.ToTable("ListaEspera");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Evolucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Conduta")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int?>("EvaAntes")
                        .HasColumnType("integer");

                    b.Property<int?>("EvaDepois")
                        .HasColumnType("integer");

                    b.Property<string>("Orientacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProfissionalId")
                        .HasColumnType("integer");

                    b.Property<string>("QueixaPrincipal")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TextoEvolucao")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("PacienteId", "Data");

                    b.ToTable("Evolucoes");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.AnexoProntuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EvolucaoId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Tamanho")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoConteudo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("EvolucaoId");

                    b.ToTable("AnexosProntuario");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ConsentimentoLgpd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concedido")
                        .HasColumnType("boolean");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VersaoTermo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "Finalidade");

                    b.ToTable("Consentimentos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("EspecialidadeConsulta")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EspecialidadeConsultaCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ModalidadeCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Numero")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Numero");

                    b.HasIndex("PacienteId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.CategoriaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CategoriasFinanceiras");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.CodigoFaturamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DataBaixa")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataGlosa")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataLimiteRecurso")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataPrevistaFaturamento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataReapresentacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EspecialidadeCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FormaObtencao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Glosa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("LoteTissId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoGlosa")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("MotivoGlosaCodigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("NaoConformidadeEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NaoConformidadeJustificativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroGuiaReal")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ObservacaoBaixa")
                        .HasColumnType("text");

                    b.Property<string>("ObservacaoPendencia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ObservacaoPendenciaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ordem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("UsuarioBaixa")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("LoteTissId");

                    b.HasIndex("DataBaixa", "DataPrevistaFaturamento");

                    b.ToTable("Codigos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ConfiguracaoGlobal", b =>
                {
                    b.Property<string>("Chave")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Chave");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Convenio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ValidadeDias")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("PacienteId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ConvenioCadastro", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaComApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CategoriaSemApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiasSegundoCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("FaturaBsv")
                        .HasColumnType("boolean");

                    b.Property<bool>("FazEletro")
                        .HasColumnType("boolean");

                    b.Property<string>("FormaSegundoCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("InverteDatasBsv")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("SegundoCodigoDependeApp")
                        .HasColumnType("boolean");

                    b.Property<bool>("TemSegundoCodigo")
                        .HasColumnType("boolean");

                    b.Property<int?>("ValidadeConsultaDias")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.EspecialidadeCadastro", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Codigo");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.EventoAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("CodigoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("LoteTissId")
                        .HasColumnType("integer");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoId");

                    b.HasIndex("DataHora");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtendimentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoriaFinanceiraId")
                        .HasColumnType("integer");

                    b.Property<int?>("CodigoFaturamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Convenio")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ConvenioCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.HasIndex("CategoriaFinanceiraId");

                    b.HasIndex("CodigoFaturamentoId");

                    b.HasIndex("Data");

                    b.HasIndex("PacienteId");

                    b.HasIndex("Status");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.LoteTiss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataEnvio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataGeracao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataRetorno")
                        .HasColumnType("date");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("ObservacaoRetorno")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProtocoloOperadora")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("RegistroAnsOperadora")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("LotesTiss");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ModalidadeCadastro", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Codigo");

                    b.ToTable("Modalidades");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Carteirinha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Convenio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ConvenioCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FotoAtualizadaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("FotoMiniatura")
                        .HasColumnType("bytea");

                    b.Property<string>("ModalidadePreferida")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ModalidadePreferidaCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<bool>("PossuiApp")
                        .HasColumnType("boolean");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly?>("ValidadeCarteirinha")
                        .HasColumnType("date");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.AutorizacaoSessoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Convenio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ConvenioCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataValidade")
                        .HasColumnType("date");

                    b.Property<bool>("Encerrada")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeAutorizada")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeUtilizadaManual")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataValidade");

                    b.HasIndex("PacienteId");

                    b.ToTable("Autorizacoes");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.PacienteFoto", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("PacienteId");

                    b.ToTable("PacientesFotos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ParametroConvenio", b =>
                {
                    b.Property<string>("Convenio")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaComApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CategoriaSemApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiasSegundoCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("ValidadeConsultaDias")
                        .HasColumnType("integer");

                    b.HasKey("Convenio");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica.Domain.Entities.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atendimento");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ListaEspera", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica.Domain.Entities.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agendamento");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Evolucao", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica.Domain.Entities.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agendamento");

                    b.Navigation("Atendimento");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.AnexoProntuario", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Evolucao", "Evolucao")
                        .WithMany("Anexos")
                        .HasForeignKey("EvolucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evolucao");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.ConsentimentoLgpd", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.CodigoFaturamento", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Atendimento", "Atendimento")
                        .WithMany("Codigos")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica.Domain.Entities.LoteTiss", "Lote")
                        .WithMany("Codigos")
                        .HasForeignKey("LoteTissId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atendimento");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.AutorizacaoSessoes", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.PacienteFoto", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithOne("Foto")
                        .HasForeignKey("Clinica.Domain.Entities.PacienteFoto", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.LancamentoFinanceiro", b =>
                {
                    b.HasOne("Clinica.Domain.Entities.Atendimento", "Atendimento")
                        .WithMany()
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.CategoriaFinanceira", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaFinanceiraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.CodigoFaturamento", "CodigoFaturamento")
                        .WithMany()
                        .HasForeignKey("CodigoFaturamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinica.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atendimento");

                    b.Navigation("Categoria");

                    b.Navigation("CodigoFaturamento");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Atendimento", b =>
                {
                    b.Navigation("Codigos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Evolucao", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.LoteTiss", b =>
                {
                    b.Navigation("Codigos");
                });

            modelBuilder.Entity("Clinica.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Consultas");

                    b.Navigation("Foto");
                });
#pragma warning restore 612, 618
        }
    }
}
