using System.Collections;
using Clinica.Desktop.Shell.Web;
using Clinica.Domain.Entities;
using Clinica.Recepcao.ViewModels;
using Microsoft.Extensions.DependencyInjection;
using P = Clinica.Desktop.Shell.Web.PaginasWebController;
namespace Clinica.Recepcao.Web;
public static partial class RecepcaoWebRegistro
{
    private static IEnumerable<P.Pagina> CriarPaginasBase()
    {
        // Contrato de PainelView.xaml; campos e comandos são constantes de apresentação.
        yield return new("painel-recepcao", "Início", typeof(PainelViewModel),
            [new P.Campo("Dia", "Dia", "leitura", Visivel: null),
             new P.Campo("Agendados", "Agendados", "leitura", Visivel: null),
             new P.Campo("VariacaoAgendados.Texto", "Texto", "leitura", Visivel: null),
             new P.Campo("VariacaoAgendados.Rotulo", "Rotulo", "leitura", Visivel: null),
             new P.Campo("AAtender", "AAtender", "leitura", Visivel: null),
             new P.Campo("EmAtendimento", "Em Atendimento", "leitura", Visivel: null),
             new P.Campo("Atendidos", "Atendidos", "leitura", Visivel: null),
             new P.Campo("VariacaoAtendidos.Texto", "Texto", "leitura", Visivel: null),
             new P.Campo("VariacaoAtendidos.Rotulo", "Rotulo", "leitura", Visivel: null),
             new P.Campo("Faltas", "Faltas", "leitura", Visivel: null),
             new P.Campo("VariacaoFaltas.Texto", "Texto", "leitura", Visivel: null),
             new P.Campo("VariacaoFaltas.Rotulo", "Rotulo", "leitura", Visivel: null),
             new P.Campo("TaxaFalta", "Taxa Falta", "leitura", Visivel: null),
             new P.Campo("VariacaoTaxaFalta.Texto", "Texto", "leitura", Visivel: null),
             new P.Campo("VariacaoTaxaFalta.Rotulo", "Rotulo", "leitura", Visivel: null),
             new P.Campo("Encaixes", "Encaixes", "leitura", Visivel: null),
             new P.Campo("ListaDeEspera", "Lista De Espera", "leitura", Visivel: null)], [],
            [
                new P.Secao("Ocupacao", "Ocupacao", null, [], [],
                    [PT("Ocupacao", [new P.Coluna("Nome", "Nome"), new P.Coluna("Horarios", "Horarios"), new P.Coluna("Carga", "Carga"), new P.Coluna("Faltas", "Faltas")], [], [], null)], []),
                new P.Secao("Pendencias", "Pendencias", null, [], [],
                    [PT("Pendencias", [new P.Coluna("Paciente", "Paciente"), new P.Coluna("Descricao", "Descricao"), new P.Coluna("Atraso", "Atraso")], [], [new P.Acao("CobrarGuia", "WhatsApp", Guarda: "TemTelefone", SemParametro: false, Visivel: null, Parametro: null)], null)], []),
                new P.Secao("Aniversariantes", "Aniversariantes", null, [], [],
                    [PT("Aniversariantes", [new P.Coluna("Paciente", "Paciente"), new P.Coluna("Detalhe", "Detalhe")], [], [new P.Acao("Parabenizar", "Parabenizar", Guarda: "TemTelefone", SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("DiaAnterior", "Dia anterior", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("ProximoDia", "Próximo dia", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Hoje", "Hoje", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Carregar", "Atualizar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], Permissao: Permissao.VerAgenda, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<PainelViewModel>(), "painel-recepcao"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de AgendaView.xaml; campos e comandos são constantes de apresentação.
        yield return new("agenda-recepcao", "Agenda", typeof(AgendaViewModel),
            [new P.Campo("ResumoPlanejamento", "Agenda", "leitura", Visivel: null),
             new P.Campo("FiltroProfissional", "Profissional da agenda", "selecao", Opcoes: "FiltroProfissionais", RotuloOpcao: "Nome", ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("ModalidadePlanejamento", "Modalidade para agendar", "selecao", Opcoes: "ModalidadesPlanejamento", RotuloOpcao: "Nome", ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("DuracaoPlanejamento", "Duração para consultar vagas", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("FiltroSala", "Sala da agenda", "selecao", Opcoes: "FiltroSalas", RotuloOpcao: "Nome", ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("UltimaLeitura", "Disponibilidade não verificada", "leitura", Visivel: "DisponibilidadeNaoVerificada"),
             new P.Campo("Dia", "Data da agenda", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("ProfissionalEmFocoNome", "Profissional Em Foco Nome", "leitura", Visivel: null),
             new P.Campo("JornadaPlanejamento", "Jornada Planejamento", "leitura", Visivel: null),
             new P.Campo("TravaPlanejamento", "Trava Planejamento", "leitura", Visivel: null),
             new P.Campo("SalaPlanejamento", "Disponibilidade", "leitura", Visivel: null),
             new P.Campo("AgruparPorSala", "Por sala", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeAgruparPorSala", Visivel: null),
             new P.Campo("Resumo", "Resumo", "leitura", Visivel: null),
             new P.Campo("EstadoVagas", "Estado Vagas", "leitura", Visivel: null)], [],
            [
                new P.Secao("ReguaPlanejamento", "Regua Planejamento", null, [], [],
                    [PT("ReguaPlanejamento", [new P.Coluna("Rotulo", "Rotulo")], [], [], null)], []),
                new P.Secao("ColunasPlanejamento", "Colunas Planejamento", null, [], [],
                    [PT("ColunasPlanejamento", [new P.Coluna("Nome", "Nome"), new P.Coluna("Resumo", "Resumo")], [], [], null)], []),
                new P.Secao("VagasPlanejamento", "Vagas Planejamento", null, [], [],
                    [PT("VagasPlanejamento", [new P.Coluna("Inicio", "Inicio"), new P.Coluna("Fim", "Fim")], [], [new P.Acao("EscolherVagaPlanejamento", "Escolher Vaga Planejamento", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("ConfigurarHorarios", "Horários e travas", Guarda: "PodeEditarAgenda", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("MarcarAtendimento", "Agendar", Guarda: "PodeMarcarAtendimento", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("BuscarVagasPlanejamento", "Próximas vagas", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("AbrirEspera", "Abrir Espera", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("ConfirmarSessoes", "Confirmar amanhã…", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("ConciliarAgenda", "Conferir atendimentos…", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("ImprimirAgenda", "Imprimir folha", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("FecharAgenda", "Fechar agenda…", Guarda: "PodeEditarAgenda", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("NovoHorario", "Novo horário", Guarda: "PodeEditarAgenda", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Carregar", "Tentar novamente", Guarda: null, SemParametro: false, Visivel: "DisponibilidadeNaoVerificada", Parametro: null),
             new P.Acao("Hoje", "Ir para hoje", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("DiaAnterior", "Período anterior", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("ProximoDia", "Próximo período", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("VerDiaPlanejamento", "Dia", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("VerSemanaPlanejamento", "Semana", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], Permissao: Permissao.VerAgenda, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<AgendaViewModel>(), "agenda-recepcao"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de FilaView.xaml; campos e comandos são constantes de apresentação.
        yield return new("fila", "Agenda do dia", typeof(FilaViewModel),
            [new P.Campo("Dia", "Dia", "leitura", Visivel: null),
             new P.Campo("Atendidos", "Atendidos", "leitura", Visivel: null),
             new P.Campo("EmSala", "Em Sala", "leitura", Visivel: null),
             new P.Campo("FaltasCancelamentos", "Faltas Cancelamentos", "leitura", Visivel: null)], [],
            [
                new P.Secao("Profissionais", "Profissionais", null, [], [],
                    [PT("Profissionais", [new("Nome", "Profissional"), new("Quantidade", "Horários"), new("Ativo", "Filtro ativo", "booleano")], [], [new P.Acao("Filtrar", "Ver agenda deste profissional", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], "TemFiltroProfissional")], []),
                new P.Secao("Linhas", "Linhas", null, [], [],
                    [PT("Linhas", [new P.Coluna("Horario", "Horário"), new P.Coluna("Paciente", "Paciente"), new P.Coluna("ContextoDaLista", "Contexto Da Lista"), new P.Coluna("Profissional", "Profissional"), new P.Coluna("Sala", "Sala"), new P.Coluna("Observacoes", "Recado escrito pela recepção neste horário"), new P.Coluna("Status", "Status"), new P.Coluna("StatusDetalhe", "Status Detalhe")], [], [new P.Acao("Avancar", "Avancar", Guarda: null, SemParametro: false, Visivel: "TemProximoPasso", Parametro: null), new P.Acao("EditarHorario", "Editar", Guarda: null, SemParametro: false, Visivel: "EmAberto", Parametro: null)], null)], []),
            ],
            [new P.Acao("DiaAnterior", "Dia anterior", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("ProximoDia", "Próximo dia", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Hoje", "Hoje", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Carregar", "Atualizar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("MarcarAtendimento", "Marcar atendimento", Guarda: "PodeMarcarAtendimento", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("NovoHorario", "Novo horário", Guarda: "PodeMarcar", SemParametro: false, Visivel: null, Parametro: null)], Permissao: Permissao.VerAgenda, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<FilaViewModel>(), "fila"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de PacientesView.xaml; campos e comandos são constantes de apresentação.
        yield return new("pacientes-recepcao", "Pacientes", typeof(PacientesViewModel),
            [new P.Campo("FiltroEscolhido", "Filtrar pacientes", "selecao", Opcoes: "Filtros", RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "MostrandoLista"),
             new P.Campo("Seletor.Termo", "Buscar por nome ou CPF", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "MostrandoLista"),
             new P.Campo("Resumo", "Resumo", "leitura", Visivel: "MostrandoLista"),
             new P.Campo("Seletor.Erro", "Erro", "leitura", Visivel: "MostrandoLista"),
             new P.Campo("Seletor.Selecionado", "Paciente", "selecao", "Seletor.Resultados", "Nome")], [],
            [
                new P.Secao("Seletor.Resultados", "Resultados", null, [], [],
                    [PT("Seletor.Resultados", [], [], [], "Seletor.AlgoFoiPedido&MostrandoLista")], []),
            ],
            [new P.Acao("Seletor.DesligarSugestao", "Ver todos", Guarda: null, SemParametro: false, Visivel: "MostrandoLista", Parametro: null),
             new P.Acao("NovoPaciente", "Novo paciente", Guarda: "PodeEditarCadastro", SemParametro: false, Visivel: "MostrandoLista", Parametro: null)], Permissao: Permissao.VerFichaPaciente, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<PacientesViewModel>(), "pacientes-recepcao"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de NovoAtendimentoView.xaml; campos e comandos são constantes de apresentação.
        yield return new("marcar-horario", "Marcar horário", typeof(NovoAtendimentoViewModel),
            [new P.Campo("TituloTela", "Titulo Tela", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("SubtituloTela", "Subtitulo Tela", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("Seletor.Termo", "Buscar paciente por nome ou CPF"),
             new P.Campo("Seletor.Selecionado", "Paciente", "selecao", "Seletor.Resultados", "Nome"),
             new P.Campo("PacienteSelecionado.Nome", "Nome", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("MetaPaciente", "Meta Paciente", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("ConvenioPaciente", "CONVÊNIO", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("CarteirinhaPaciente", "CARTEIRINHA", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("CategoriaPaciente", "CATEGORIA", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("TituloPassoQuando", "Titulo Passo Quando", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("Data", "Data", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "PacienteEscolhido"),
             new P.Campo("Hora", "Hora da sessão — do encaixe de agora ou do horário marcado.", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "PacienteEscolhido"),
             new P.Campo("Profissional", "Escolha o profissional", "selecao", Opcoes: "Profissionais", RotuloOpcao: "Rotulo", ValorOpcao: null, Guarda: null, Visivel: "PacienteEscolhido"),
             new P.Campo("Duracao", "Vazio usa a duração padrão do profissional.", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "MarcarParaDepois&PacienteEscolhido"),
             new P.Campo("Sala", "Opcional", "selecao", Opcoes: "Salas", RotuloOpcao: "Nome", ValorOpcao: null, Guarda: null, Visivel: "PacienteEscolhido"),
             new P.Campo("CabecalhoDosAvisos", "Cabecalho Dos Avisos", "leitura", Visivel: "TemConflitoMarcacao&MarcarParaDepois&PacienteEscolhido"),
             new P.Campo("ComoEncaixe", "Registrar como encaixe (atender por cima de um horário que já tem paciente)", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "TemConflitoMarcacao&MarcarParaDepois&PacienteEscolhido"),
             new P.Campo("TituloPasso2", "Titulo Passo2", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("EspecialidadeSelecionada", "Especialidade da consulta", "selecao", Opcoes: "Especialidades", RotuloOpcao: "Nome", ValorOpcao: null, Guarda: null, Visivel: "ModalidadeConsulta&PacienteEscolhido"),
             new P.Campo("PrimeiroCodigo", "Qual código libera primeiro?", "selecao", Opcoes: "OpcoesPrimeiroCodigo", RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "ModalidadeDupla&PacienteEscolhido"),
             new P.Campo("Observacoes", "Opcional — fica no atendimento e na capa.", "textarea", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "PacienteEscolhido"),
             new P.Campo("TituloResultado", "Titulo Resultado", "leitura", Visivel: "Lancado&PacienteEscolhido"),
             new P.Campo("ResumoBaixas", "Resumo Baixas", "leitura", Visivel: "Lancado&PacienteEscolhido"),
             new P.Campo("AtendimentoJaRealizado", "O atendimento já aconteceu — registrar como realizado", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "LancarAgora&PacienteEscolhido"),
             new P.Campo("AvisoJaLancado", "Aviso Ja Lancado", "leitura", Visivel: "TemAvisoJaLancado&PacienteEscolhido"),
             new P.Campo("AvisoHorarioDoDia", "Aviso Horario Do Dia", "leitura", Visivel: "TemAvisoHorarioDoDia&PacienteEscolhido"),
             new P.Campo("CriarEncaixeSeparado", "Criar um encaixe separado (o horário continua na agenda)", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: "MostrarEscolhaEncaixe&TemAvisoHorarioDoDia&PacienteEscolhido"),
             new P.Campo("AvisoCarteirinha", "Aviso Carteirinha", "leitura", Visivel: "TemAvisoCarteirinha&PacienteEscolhido"),
             new P.Campo("AvisoConsulta", "Aviso Consulta", "leitura", Visivel: "TemAvisoConsulta&PacienteEscolhido"),
             new P.Campo("SaldoAutorizacao", "Saldo Autorizacao", "leitura", Visivel: "TemSaldoAutorizacao&PacienteEscolhido"),
             new P.Campo("AvisoPendencias", "Aviso Pendencias", "leitura", Visivel: "TemAvisoPendencias&PacienteEscolhido"),
             new P.Campo("ValorPrevisto", "O PAGAMENTO", "leitura", Visivel: "PacienteEscolhido"),
             new P.Campo("ResumoCurtoPrevia", "Resumo Curto Previa", "leitura", Visivel: "MostrarPrevia&PacienteEscolhido"),
             new P.Campo("ValidadePaciente", "Validade Paciente", "leitura", Visivel: "GuiaAberta&MostrarPrevia&PacienteEscolhido"),
             new P.Campo("ExecutanteGuia", "Executante Guia", "leitura", Visivel: "GuiaAberta&MostrarPrevia&PacienteEscolhido"),
             new P.Campo("ResumoPrevia", "Resumo Previa", "leitura", Visivel: "GuiaAberta&MostrarPrevia&PacienteEscolhido"),
             new P.Campo("NotaGuiaNaMarcacao", "Nota Guia Na Marcacao", "leitura", Visivel: "MarcarParaDepois&PacienteEscolhido")], [],
            [
                new P.Secao("ConflitosMarcacao", "Conflitos Marcacao", null, [], [],
                    [PT("ConflitosMarcacao", [new P.Coluna("Texto", "Texto")], [], [], "TemConflitoMarcacao&MarcarParaDepois&PacienteEscolhido")], []),
                new P.Secao("Cartoes", "Cartoes", null, [], [],
                    [PT("Cartoes", [new P.Coluna("Nome", "Nome"), new P.Coluna("QuantasGuias", "Quantas Guias"), new P.Coluna("Quando", "Quando")], [], [new P.Acao("EscolherModalidade", "Escolher Modalidade", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], "PacienteEscolhido")], []),
                new P.Secao("CodigosGerados", "Codigos Gerados", null, [], [],
                    [PT("CodigosGerados", [new P.Coluna("TipoRotulo", "Tipo Rotulo"), new P.Coluna("Situacao", "Situacao"), new P.Coluna("EspecialidadeRotulo", "Especialidade Rotulo"), new P.Coluna("OrdemRotulo", "Ordem Rotulo"), new P.Coluna("FaturarEm", "Faturar Em"), new P.Coluna("ComoObter", "Como Obter")], [], [], "Lancado&PacienteEscolhido")], []),
                new P.Secao("Avisos", "Avisos", null, [], [],
                    [PT("Avisos", [new P.Coluna(".", "")], [], [], "Lancado&PacienteEscolhido")], []),
                new P.Secao("AlertasElegibilidade", "Alertas Elegibilidade", null, [], [],
                    [PT("AlertasElegibilidade", [new P.Coluna("Descricao", "Descricao")], [], [new P.Acao("ReceberDivida", "Receber…", Guarda: null, SemParametro: true, Visivel: "PodeReceber", Parametro: null)], "PacienteEscolhido")], []),
                new P.Secao("Previa", "Previa", null, [], [],
                    [PT("Previa", [new P.Coluna("Tipo", "Tipo"), new P.Coluna("Ordem", "Ordem"), new P.Coluna("FaturarEm", "Faturar Em"), new P.Coluna("ComoObter", "Como Obter"), new P.Coluna("Especialidade", "Especialidade"), new P.Coluna("Nota", "Nota")], [], [], "GuiaAberta&MostrarPrevia&PacienteEscolhido")], []),
            ],
            [new P.Acao("Seletor.DesligarSugestao", "Ver todos"),
             new P.Acao("TrocarPaciente", "Trocar", Guarda: null, SemParametro: false, Visivel: "PacienteEscolhido", Parametro: null),
             new P.Acao("ProximasVagas", "Próximas vagas…", Guarda: "PodeBuscarVagas", SemParametro: false, Visivel: "MarcarParaDepois&PacienteEscolhido", Parametro: null),
             new P.Acao("GerarCapa", "Capa inicial (PDF)", Guarda: null, SemParametro: false, Visivel: "Lancado&PacienteEscolhido", Parametro: null),
             new P.Acao("Lancar", "Lancar", Guarda: "PodeLancar", SemParametro: false, Visivel: "PacienteEscolhido", Parametro: null),
             new P.Acao("NovoLancamento", "Novo Lancamento", Guarda: null, SemParametro: false, Visivel: "Lancado&PacienteEscolhido", Parametro: null),
             new P.Acao("EscolherConvenio", "Escolher convênio…", Guarda: null, SemParametro: false, Visivel: "SemConvenio&PacienteEscolhido", Parametro: null),
             new P.Acao("VenderPacote", "Vender pacote…", Guarda: null, SemParametro: false, Visivel: "MostrarVenderPacote&PacienteEscolhido", Parametro: null),
             new P.Acao("AlternarGuia", "Alternar Guia", Guarda: null, SemParametro: false, Visivel: "MostrarPrevia&PacienteEscolhido", Parametro: null)], Permissao: Permissao.EditarAgenda, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<NovoAtendimentoViewModel>(), "marcar-horario"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de ConsultasView.xaml; campos e comandos são constantes de apresentação.
        yield return new("consultas", "Consultas de convênio", typeof(ConsultasViewModel),
            [new P.Campo("Resumo", "Resumo", "leitura", Visivel: null),
             new P.Campo("FiltroSituacao", "Situação", "selecao", Opcoes: "OpcoesSituacao", RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("FiltroConvenio", "Convênio", "selecao", Opcoes: "Convenios", RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("FiltroPaciente", "Parte do nome — o acento não atrapalha", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null)], [],
            [
                new P.Secao("Consultas", "Consultas", null, [], [],
                    [PT("Consultas", [new P.Coluna("Paciente", "Paciente"), new P.Coluna("Situacao", "Situacao"), new P.Coluna("Convenio", "Convenio"), new P.Coluna("Vencimento", "Vencimento")], [], [new P.Acao("Renovar", "Renovar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("Recarregar", "Atualizar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("LimparFiltro", "Limpar filtro", Guarda: "FiltroAtivo", SemParametro: false, Visivel: null, Parametro: null)], Permissao: Permissao.VerFichaPaciente, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<ConsultasViewModel>(), "consultas"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de LancamentosView.xaml; campos e comandos são constantes de apresentação.
        yield return new("lancamentos", "Lançamentos", typeof(LancamentosViewModel),
            [new P.Campo("De", "De", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Ate", "Até", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Convenio", "Convênio", "selecao", Opcoes: "ConveniosDisponiveis", RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Modalidade", "Modalidade", "selecao", Opcoes: "ModalidadesDisponiveis", RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Operador", "Quem lançou", "selecao", Opcoes: "OperadoresDisponiveis", RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("SomenteComPendencia", "Só com guia por liberar", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Resumo", "Resumo", "leitura", Visivel: null)], [],
            [
                new P.Secao("Linhas", "Linhas", null, [], [],
                    [PT("Linhas", [new P.Coluna("DataRotulo", "DIA"), new P.Coluna("Paciente", "Paciente"), new P.Coluna("Modalidade", "Modalidade"), new P.Coluna("Lancamento", "Lancamento"), new P.Coluna("Guias", "Guias"), new P.Coluna("Pendencia", "Pendencia"), new P.Coluna("Numero", "ATENDIMENTO"), new P.Coluna("Convenio", "Convenio")], [], [new P.Acao("Estornar", "Estornar…", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("Buscar", "Atualizar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("LimparFiltros", "Limpar filtros", Guarda: null, SemParametro: false, Visivel: "TemFiltro", Parametro: null)], Permissao: Permissao.LancarAtendimento, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<LancamentosViewModel>(), "lancamentos"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de RetornosAMarcarView.xaml; campos e comandos são constantes de apresentação.
        yield return new("retornos-a-marcar", "Retornos a marcar", typeof(RetornosAMarcarViewModel),
            [new P.Campo("Resumo", "Resumo", "leitura", Visivel: null)], [],
            [
                new P.Secao("Linhas", "Linhas", null, [], [],
                    [PT("Linhas", [new P.Coluna("RetornoEm", "Retorno Em"), new P.Coluna("Situacao", "Situacao"), new P.Coluna("Paciente", "Paciente"), new P.Coluna("Telefone", "Telefone"), new P.Coluna("Sessao", "Sessao"), new P.Coluna("Profissional", "Profissional"), new P.Coluna("Nota", "Nota")], [], [new P.Acao("Marcar", "Marcar horário", Guarda: null, SemParametro: false, Visivel: null, Parametro: null), new P.Acao("WhatsApp", "WhatsApp", Guarda: "TemTelefone", SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("Carregar", "Atualizar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], Permissao: Permissao.EditarAgenda, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<RetornosAMarcarViewModel>(), "retornos-a-marcar"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de AcompanhamentoView.xaml; campos e comandos são constantes de apresentação.
        yield return new("retorno-pacientes", "Acompanhamento de pacientes", typeof(AcompanhamentoViewModel),
            [new P.Campo("DiasRecall", "Dias sem retornar para buscar", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "EhRecall&ListaVisivel"),
             new P.Campo("Busca", "Buscar paciente pelo nome", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "ListaVisivel"),
             new P.Campo("Situacao", "Situação do acompanhamento", "selecao", Opcoes: "EstadosFila", RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "ListaVisivel"),
             new P.Campo("Modalidade", "Modalidade do recall", "selecao", Opcoes: "Modalidades", RotuloOpcao: "Nome", ValorOpcao: "Codigo", Guarda: "PodeInteragir", Visivel: "ListaVisivel"),
             new P.Campo("FiltrosAtivos", "Filtros Ativos", "leitura", Visivel: "ListaVisivel"),
             new P.Campo("Resumo", "Resumo", "leitura", Visivel: "ListaVisivel"),
             new P.Campo("Prazo", "Prazo do próximo contato", "selecao", Opcoes: "Prazos", RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("Condicao", "Condição especial", "selecao", Opcoes: "Condicoes", RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("Convenio", "Convênio", "selecao", Opcoes: "Convenios", RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("Profissional", "Profissional", "selecao", Opcoes: "ProfissionaisFiltro", RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("ResponsavelFiltro", "Funcionária responsável", "selecao", Opcoes: "ResponsaveisFiltro", RotuloOpcao: "Nome", ValorOpcao: "Id", Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("DiasMinimos", "Dias mínimos", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("DiasMaximos", "Dias máximos", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("MotivoFiltro", "Filtrar motivo", "selecao", Opcoes: "MotivosFiltro", RotuloOpcao: "Nome", ValorOpcao: "Id", Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("TentativasMinimas", "Mínimo de tentativas", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("ContatoDesde", "Último contato desde", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("ContatoAte", "Último contato até", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("SomenteMeus", "Somente meus pacientes", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Filtrando"),
             new P.Campo("Selecionado.Paciente", "Paciente", "leitura", Visivel: "DetalheVisivel"),
             new P.Campo("Selecionado.ModalidadeTexto", "Modalidade Texto", "leitura", Visivel: "DetalheVisivel"),
             new P.Campo("Selecionado.Situacao", "Situacao", "leitura", Visivel: "DetalheVisivel"),
             new P.Campo("Selecionado.Marcadores", "Marcadores", "leitura", Visivel: "DetalheVisivel"),
             new P.Campo("Selecionado.MotivoEncerramento", "Motivo Encerramento", "leitura", Visivel: "DetalheVisivel"),
             new P.Campo("ResponsavelContato", "Responsável pelo contato — usuário conectado", "leitura", Visivel: "DetalheVisivel"),
             new P.Campo("EtapaEdicao", "Resultado do contato", "selecao", Opcoes: "Etapas", RotuloOpcao: "Nome", ValorOpcao: "Codigo", Guarda: "PodeInteragir", Visivel: "DetalheVisivel"),
             new P.Campo("CanalEdicao", "Canal utilizado", "selecao", Opcoes: "Canais", RotuloOpcao: "Nome", ValorOpcao: "Codigo", Guarda: "PodeInteragir", Visivel: "DetalheVisivel"),
             new P.Campo("ProximoContato", "Data do próximo contato", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "DetalheVisivel"),
             new P.Campo("MotivoEdicao", "Motivo do acompanhamento", "selecao", Opcoes: "MotivosEdicao", RotuloOpcao: "Nome", ValorOpcao: "Id", Guarda: "PodeInteragir", Visivel: "DetalheVisivel"),
             new P.Campo("Observacao", "Resultado do contato, motivo e próximo passo", "textarea", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "DetalheVisivel"),
             new P.Campo("Encerrar", "Encerrar por não conformidade (exige motivo e justificativa)", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "DetalheVisivel"),
             new P.Campo("Reabrir", "Reabrir acompanhamento encerrado", "booleano", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "DetalheVisivel"),
             new P.Campo("ConfiguracaoTexto", "Configuracao Texto", "leitura", Visivel: "Configurando"),
             new P.Campo("ProfissionalBsv", "Profissional das indicações BSV", "selecao", Opcoes: "Profissionais", RotuloOpcao: "Nome", ValorOpcao: "Id", Guarda: "PodeInteragir", Visivel: "Configurando"),
             new P.Campo("NovoMotivo", "Nome do novo motivo", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: "PodeInteragir", Visivel: "Configurando")], [],
            [
                new P.Secao("Pacientes", "Pacientes", null, [], [],
                    [PT("Pacientes", [new P.Coluna("Paciente", "Paciente"), new P.Coluna("ModalidadeTexto", "Modalidade Texto"), new P.Coluna("Convenio", "Convenio"), new P.Coluna("Telefone", "Telefone"), new P.Coluna("Situacao", "Situacao"), new P.Coluna("ProximoContato", "Proximo Contato"), new P.Coluna("ProximoPasso", "Proximo Passo"), new P.Coluna("Marcadores", "Marcadores"), new P.Coluna("AgendadoPara", "Agendado Para"), new P.Coluna("Responsavel", "Responsavel"), new P.Coluna("DiasTexto", "Dias Texto"), new P.Coluna("Tentativas", "Tentativas"), new P.Coluna("UltimoContato", "Ultimo Contato")], [], [new P.Acao("Abrir", "Abrir", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], "ListaVisivel")], []),
                new P.Secao("VisaoGestao", "Visao Gestao", null, [], [],
                    [PT("VisaoGestao", [new P.Coluna(".", "")], [], [], "Gestor&Filtrando")], []),
                new P.Secao("Historico", "Historico", null, [], [],
                    [PT("Historico", [new P.Coluna("Em", "Em"), new P.Coluna("Operador", "Operador"), new P.Coluna("Canal", "Canal"), new P.Coluna("Resultado", "Resultado"), new P.Coluna("Observacao", "Observacao"), new P.Coluna("ProximoContato", "Proximo Contato")], [], [], "DetalheVisivel")], []),
                new P.Secao("Motivos", "Motivos", null, [], [],
                    [PT("Motivos", [new P.Coluna("Nome", "Nome")], [], [], "Configurando")], []),
            ],
            [new P.Acao("TrocarAba", "Recall · pacientes sem retorno", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: "Recall"),
             new P.Acao("TrocarAba", "Novos BSV · primeira sessão", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: "BSV"),
             new P.Acao("Recarregar", "Atualizar", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: null),
             new P.Acao("Configurar", "Configurar acompanhamento", Guarda: "PodeInteragir", SemParametro: false, Visivel: "Gestor&ListaVisivel", Parametro: null),
             new P.Acao("Gerar", "Buscar pacientes", Guarda: "PodeInteragir", SemParametro: false, Visivel: "EhRecall&ListaVisivel", Parametro: null),
             new P.Acao("Atalho", "Atalho", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: "assumir"),
             new P.Acao("Atalho", "Atalho", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: "hoje"),
             new P.Acao("Atalho", "Atalho", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: "atrasados"),
             new P.Acao("Atalho", "Atalho", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: "sem-contato"),
             new P.Acao("AbrirFiltros", "Mais filtros", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: null),
             new P.Acao("LimparFiltros", "Limpar filtros", Guarda: "PodeInteragir", SemParametro: false, Visivel: "ListaVisivel", Parametro: null),
             new P.Acao("Voltar", "Aplicar filtros e voltar", Guarda: "PodeInteragir", SemParametro: false, Visivel: "Filtrando", Parametro: null),
             new P.Acao("Assumir", "Assumir acompanhamento", Guarda: "Selecionado.Pendente&PodeInteragir", SemParametro: false, Visivel: "DetalheVisivel", Parametro: null),
             new P.Acao("WhatsApp", "Abrir WhatsApp", Guarda: "Selecionado.PodeContatar&PodeInteragir", SemParametro: false, Visivel: "DetalheVisivel", Parametro: null),
             new P.Acao("Agendar", "Agendar sessão", Guarda: "PodeAgendar&PodeInteragir", SemParametro: false, Visivel: "DetalheVisivel", Parametro: null),
             new P.Acao("Salvar", "Salvar acompanhamento", Guarda: "PodeInteragir", SemParametro: false, Visivel: "DetalheVisivel", Parametro: null),
             new P.Acao("SalvarConfiguracao", "Salvar configuração", Guarda: "PodeInteragir", SemParametro: false, Visivel: "Configurando", Parametro: null),
             new P.Acao("AdicionarMotivo", "Cadastrar motivo", Guarda: "PodeInteragir", SemParametro: false, Visivel: "Configurando", Parametro: null)], Permissao: Permissao.VerFichaPaciente, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<AcompanhamentoViewModel>(), "retorno-pacientes"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de DocumentosView.xaml; campos e comandos são constantes de apresentação.
        yield return new("documentos", "Documentos", typeof(DocumentosViewModel),
            [new P.Campo("Seletor.Termo", "Quem vai receber o papel?", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("RotuloDeHoje", "Rotulo De Hoje", "leitura", Visivel: "TemGenteHoje"),
             new P.Campo("Seletor.Erro", "Erro", "leitura", Visivel: null),
             new P.Campo("Seletor.Selecionado.Nome", "Nome", "leitura", Visivel: "Seletor.Selecionado"),
             new P.Campo("IdentidadeDoPaciente", "Identidade Do Paciente", "leitura", Visivel: "Seletor.Selecionado"),
             new P.Campo("Previa.Rotulo", "Rotulo", "leitura", Visivel: "Previa"),
             new P.Campo("Previa.ParaQuem", "Para Quem", "leitura", Visivel: "Previa"),
             new P.Campo("Previa.Descricao", "Descricao", "leitura", Visivel: "Previa"),
             new P.Campo("Previa.OQueAcontece", "OQue Acontece", "leitura", Visivel: "Previa"),
             new P.Campo("Previa.OQueFalta", "OQue Falta", "leitura", Visivel: "Previa.TemPendencia&Previa"),
             new P.Campo("Previa.Garantias", "Garantias", "leitura", Visivel: "Previa"),
             new P.Campo("Resumo", "Resumo", "leitura", Visivel: null),
             new P.Campo("Inicio", "De", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Fim", "De", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Codigo", "Conferir pelo código", "texto", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Conferido", "Conferido", "leitura", Visivel: null),
             new P.Campo("Seletor.Selecionado", "Paciente", "selecao", "Seletor.Resultados", "Nome")], [],
            [
                new P.Secao("DeHoje", "De Hoje", null, [], [],
                    [PT("DeHoje", [new P.Coluna("Nome", "Nome"), new P.Coluna("Hora", "Hora")], [], [new P.Acao("EscolherDeHoje", "Escolher De Hoje", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], "TemGenteHoje")], []),
                new P.Secao("Seletor.Resultados", "Resultados", null, [], [],
                    [PT("Seletor.Resultados", [new("Nome", "Paciente"), new("Documento", "CPF / documento"), new("Telefone", "Telefone")], [], [new("EscolherPaciente", "Escolher paciente")], "Seletor.TemResultados")], []),
                new P.Secao("Folhas", "Folhas", null, [], [],
                    [PT("Folhas", [new P.Coluna("Rotulo", "Rotulo"), new P.Coluna("Descricao", "Descricao"), new P.Coluna("Pendencia", "Pendencia"), new P.Coluna("Grupo", "Grupo")], [], [new P.Acao("EscolherFolha", "Escolher Folha", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
                new P.Secao("Emitidas", "Emitidas", null, [], [],
                    [PT("Emitidas", [new P.Coluna("Numero", "Numero"), new P.Coluna("Folha", "Folha"), new P.Coluna("Para", "Para"), new P.Coluna("Detalhe", "Detalhe"), new P.Coluna("Situacao", "Situacao"), new P.Coluna("Link", "Link"), new P.Coluna("Data", "Data")], [], [new P.Acao("Assinar", "Assinar", Guarda: null, SemParametro: false, Visivel: "PodeAssinar", Parametro: null), new P.Acao("Reimprimir", "2ª via", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("TrocarPaciente", "Trocar", Guarda: null, SemParametro: false, Visivel: "Seletor.Selecionado", Parametro: null),
             new P.Acao("Gerar", "Gerar", Guarda: "Previa.PodeEmitir", SemParametro: false, Visivel: "Previa", Parametro: null),
             new P.Acao("Carregar", "Atualizar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Conferir", "Conferir", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("ReimprimirConferido", "Segunda via", Guarda: null, SemParametro: false, Visivel: "TemConferido", Parametro: null)], Permissao: Permissao.VerDocumentos, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<DocumentosViewModel>(), "documentos"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de EquipeView.xaml; campos e comandos são constantes de apresentação.
        yield return new("equipe", "Profissionais e salas", typeof(EquipeViewModel),
            [], [],
            [
                new P.Secao("Profissionais", "Profissionais", null, [], [],
                    [PT("Profissionais", [new P.Coluna("Nome", "Nome"), new P.Coluna("Registro", "Registro"), new P.Coluna("Duracao", "Duracao"), new P.Coluna("Jornada", "Jornada"), new P.Coluna("Situacao", "Situacao")], [], [new P.Acao("EditarProfissional", "Editar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null), new P.Acao("ExcluirProfissional", "Excluir", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
                new P.Secao("Salas", "Salas", null, [], [],
                    [PT("Salas", [new P.Coluna("Nome", "Nome"), new P.Coluna("Capacidade", "Capacidade"), new P.Coluna("Situacao", "Situacao")], [], [new P.Acao("EditarSala", "Editar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null), new P.Acao("ExcluirSala", "Excluir", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
                new P.Secao("Bloqueios", "Bloqueios", null, [], [],
                    [PT("Bloqueios", [new P.Coluna("Alvo", "Alvo"), new P.Coluna("Periodo", "Periodo"), new P.Coluna("Motivo", "Motivo"), new P.Coluna("Situacao", "Situacao")], [], [new P.Acao("RemarcarBloqueio", "Empurrar sessões", Guarda: null, SemParametro: false, Visivel: "TemConflito", Parametro: null), new P.Acao("ExcluirBloqueio", "Reabrir", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("NovoProfissional", "Novo profissional", Guarda: "PodeGerenciarEquipe", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("NovaSala", "Nova sala", Guarda: "PodeGerenciarEquipe", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("NovoBloqueio", "Fechar agenda…", Guarda: "PodeEditarAgenda", SemParametro: false, Visivel: null, Parametro: null)], Permissao: Permissao.GerenciarEquipe, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<EquipeViewModel>(), "equipe"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de PagamentosView.xaml; campos e comandos são constantes de apresentação.
        yield return new("pagamentos-recepcao", "Pagamentos", typeof(PagamentosViewModel),
            [new P.Campo("Seletor.Termo", "Buscar paciente por nome ou CPF"),
             new P.Campo("Seletor.Selecionado", "Paciente", "selecao", "Seletor.Resultados", "Nome"),
             new P.Campo("Paciente", "Pagamentos na recepção", "leitura", Visivel: "TemPaciente"),
             new P.Campo("Resumo", "Pagamentos na recepção", "leitura", Visivel: "TemPaciente")], [],
            [
                new P.Secao("Linhas", "Linhas", null, [], [],
                    [PT("Linhas", [new P.Coluna("Descricao", "Sessão / cobrança"), new P.Coluna("Vencimento", "Vencimento"), new P.Coluna("Valor", "Valor"), new P.Coluna("Situacao", "Situação")], [], [new P.Acao("Receber", "Receber", Guarda: null, SemParametro: false, Visivel: "EmAberto", Parametro: null), new P.Acao("Recibo", "Recibo", Guarda: null, SemParametro: false, Visivel: "Recebido", Parametro: null)], "TemPaciente")], []),
            ],
            [new P.Acao("Seletor.DesligarSugestao", "Ver todos"),
             new P.Acao("TrocarPaciente", "Trocar paciente", Guarda: null, SemParametro: false, Visivel: "TemPaciente", Parametro: null),
             new P.Acao("Carregar", "Atualizar", Guarda: null, SemParametro: false, Visivel: "TemPaciente", Parametro: null)], Permissao: Permissao.VenderPacote, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<PagamentosViewModel>(), "pagamentos-recepcao"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
        // Contrato de ConfirmacoesView.xaml; campos e comandos são constantes de apresentação.
        yield return new("agenda-confirmacoes", "Confirmações de agenda", typeof(ConfirmacoesViewModel),
            [new P.Campo("Dia", "Dia", "data", Opcoes: null, RotuloOpcao: null, ValorOpcao: null, Guarda: null, Visivel: null),
             new P.Campo("Resumo", "Confirmar sessões", "leitura", Visivel: null)], [],
            [
                new P.Secao("Contatos", "Contatos", null, [], [],
                    [PT("Contatos", [new P.Coluna("Horario", "Horario"), new P.Coluna("Paciente", "Paciente"), new P.Coluna("Profissional", "Profissional"), new P.Coluna("Situacao", "Situacao")], [], [new P.Acao("Enviar", "WhatsApp", Guarda: "TemTelefone", SemParametro: false, Visivel: null, Parametro: null), new P.Acao("Confirmou", "Confirmou", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], null)], []),
            ],
            [new P.Acao("Amanha", "Amanhã", Guarda: null, SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Gerar", "Gerar rodada", Guarda: "PodeEditar", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("EnviarEmails", "Enviar e-mails", Guarda: "PodeEditar", SemParametro: false, Visivel: null, Parametro: null),
             new P.Acao("Carregar", "Atualizar", Guarda: null, SemParametro: false, Visivel: null, Parametro: null)], Permissao: Permissao.VerAgenda, Fabrica: sp => PrepararPagina(sp, sp.GetRequiredService<ConfirmacoesViewModel>(), "agenda-confirmacoes"), AoAbrir: AbrirPaginaAsync, AoFechar: FecharPagina);
    }
    private static P.Tab PT(string origem, P.Coluna[] colunas, P.Campo[] campos, P.Acao[] acoes, string? visivel = null) =>
        new(origem, origem, [origem], vm => ColecaoWeb(vm, origem), colunas, campos, acoes, Visivel: visivel);
    private static IEnumerable<object> ColecaoWeb(object vm, string caminho)
    {
        object? valor = vm; foreach (var parte in caminho.Split('.')) valor = valor?.GetType().GetProperty(parte)?.GetValue(valor);
        return (valor as IEnumerable)?.Cast<object>() ?? [];
    }
}
