START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE TABLE "MotivosAcompanhamento" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" character varying(100) NOT NULL,
        "Ativo" boolean NOT NULL,
        CONSTRAINT "PK_MotivosAcompanhamento" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE TABLE "Acompanhamentos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PacienteId" integer NOT NULL,
        "Tipo" character varying(20) NOT NULL,
        "Modalidade" character varying(40) NOT NULL,
        "ReferenciaEm" timestamp without time zone NOT NULL,
        "AgendamentoOrigemId" integer,
        "ProfissionalId" integer,
        "ResponsavelId" integer,
        "ProximoContato" date NOT NULL,
        "Etapa" character varying(30) NOT NULL,
        "CriadoEm" timestamp without time zone NOT NULL,
        "CriadoPor" character varying(80) NOT NULL,
        "EncerradoEm" timestamp without time zone,
        "MotivoEncerramento" character varying(2000),
        "EncerradoPor" character varying(80),
        "MotivoId" integer,
        "Versao" uuid NOT NULL,
        CONSTRAINT "PK_Acompanhamentos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Acompanhamentos_Agendamentos_AgendamentoOrigemId" FOREIGN KEY ("AgendamentoOrigemId") REFERENCES "Agendamentos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Acompanhamentos_MotivosAcompanhamento_MotivoId" FOREIGN KEY ("MotivoId") REFERENCES "MotivosAcompanhamento" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Acompanhamentos_Pacientes_PacienteId" FOREIGN KEY ("PacienteId") REFERENCES "Pacientes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Acompanhamentos_Profissionais_ProfissionalId" FOREIGN KEY ("ProfissionalId") REFERENCES "Profissionais" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Acompanhamentos_Usuarios_ResponsavelId" FOREIGN KEY ("ResponsavelId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE TABLE "ContatosAcompanhamento" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AcompanhamentoPacienteId" integer NOT NULL,
        "Idempotencia" uuid NOT NULL,
        "Em" timestamp without time zone NOT NULL,
        "Operador" character varying(80) NOT NULL,
        "Canal" character varying(20),
        "Resultado" character varying(100) NOT NULL,
        "Observacao" character varying(2000) NOT NULL,
        "ProximoContato" date,
        "ResponsavelId" integer,
        CONSTRAINT "PK_ContatosAcompanhamento" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ContatosAcompanhamento_Acompanhamentos_AcompanhamentoPacien~" FOREIGN KEY ("AcompanhamentoPacienteId") REFERENCES "Acompanhamentos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ContatosAcompanhamento_Usuarios_ResponsavelId" FOREIGN KEY ("ResponsavelId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE INDEX "IX_Acompanhamentos_AgendamentoOrigemId" ON "Acompanhamentos" ("AgendamentoOrigemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE INDEX "IX_Acompanhamentos_MotivoId" ON "Acompanhamentos" ("MotivoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE UNIQUE INDEX "IX_Acompanhamentos_PacienteId_Tipo_Modalidade" ON "Acompanhamentos" ("PacienteId", "Tipo", "Modalidade");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE INDEX "IX_Acompanhamentos_ProfissionalId" ON "Acompanhamentos" ("ProfissionalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE INDEX "IX_Acompanhamentos_ResponsavelId_ProximoContato" ON "Acompanhamentos" ("ResponsavelId", "ProximoContato");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE UNIQUE INDEX "IX_ContatosAcompanhamento_AcompanhamentoPacienteId_Idempotencia" ON "ContatosAcompanhamento" ("AcompanhamentoPacienteId", "Idempotencia");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE INDEX "IX_ContatosAcompanhamento_ResponsavelId" ON "ContatosAcompanhamento" ("ResponsavelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    CREATE UNIQUE INDEX "IX_MotivosAcompanhamento_Nome" ON "MotivosAcompanhamento" ("Nome");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    INSERT INTO "MotivosAcompanhamento" ("Nome", "Ativo") VALUES
    ('Aguardando autorização do plano', TRUE),
    ('Plano negou autorização', TRUE),
    ('Paciente pediu adiamento', TRUE),
    ('Desistência informada pelo paciente', TRUE),
    ('Telefone desatualizado', TRUE);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928123100_AcompanhamentoPacientesBsvRecall') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260928123100_AcompanhamentoPacientesBsvRecall', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928210520_DiluicaoUnicaInfusao') THEN
    ALTER TABLE "PrescricoesInternas" ADD "DiluenteGlobal" character varying(120);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928210520_DiluicaoUnicaInfusao') THEN
    ALTER TABLE "PrescricoesInternas" ADD "DiluicaoUnica" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928210520_DiluicaoUnicaInfusao') THEN
    ALTER TABLE "PrescricoesInternas" ADD "VolumeTotal" character varying(60);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928210520_DiluicaoUnicaInfusao') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260928210520_DiluicaoUnicaInfusao', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928211121_ChecagemNaoExecutavel') THEN
    ALTER TABLE "ChecagensPrescricao" ADD "NaoExecutavel" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260928211121_ChecagemNaoExecutavel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260928211121_ChecagemNaoExecutavel', '8.0.11');
    END IF;
END $EF$;
COMMIT;

