using Secao = Clinica.Desktop.Shell.Web.PaginasWebController.Secao;
using System.Collections;
using System.Globalization;
using Clinica.Desktop.ViewModels;
using Clinica.Desktop.Shell.Modulos;
using Clinica.Desktop.Shell.Web;
using Clinica.Domain.Entities;
using Microsoft.Extensions.DependencyInjection;
using static Clinica.Desktop.Shell.Web.PaginasWebController;
namespace Clinica.Faturamento.Web;
public static partial class FaturamentoWebRegistro
{
    private static Campo F(string p,string rotulo,string tipo="texto",string? opcoes=null,Permissao permissao=Permissao.Nenhuma,string? guarda=null) => new(p,rotulo,tipo,opcoes,Permissao:permissao,Guarda:guarda);
    private static Acao A(string c,string rotulo,Permissao permissao=Permissao.Nenhuma,string? guarda=null) => new(c,rotulo,permissao,guarda);
    private static IEnumerable<object> Lista(object vm,string nome) => ((IEnumerable?)vm.GetType().GetProperty(nome)?.GetValue(vm))?.Cast<object>() ?? [];
    private static Tab T(string nome,string titulo,string colunas,Acao[] acoes,Campo[]? campos=null) => new(nome,titulo,[nome],vm=>Lista(vm,nome),colunas.Split(';').Select(c=>{var p=c.Split('|');return new Coluna(p[0],p.Length>1?p[1]:p[0],p[0] is "Urgencia" or "SituacaoGuia" or "StatusRotulo" ? "status":"texto");}).ToArray(),campos ?? [],acoes,
        (vm,row,c) => c=="Urgencia" ? PaginasWebController.Ler(row,"Urgencia")?.ToString() switch { "Vermelho"=>"Atrasada", "Amarelo"=>"No prazo", "Verde"=>"Em dia", "Cinza"=>"Não conformidade", _=>null } : c=="SituacaoGuia" ? new Clinica.Desktop.Converters.StatusCodigoConverter().Convert(row,typeof(string),null!,CultureInfo.GetCultureInfo("pt-BR"))?.ToString() : c=="Selecionada" && vm is DashboardViewModel d ? d.EstaSelecionada(row) ? "Selecionada" : "Não selecionada" : null);
    private static Secao S(string chave,string titulo,Tab[] tabelas,Campo[]? campos=null,Acao[]? acoes=null,string? descricao=null) => new(chave,titulo,descricao,campos ?? [],[],tabelas,acoes ?? []);
    public static IEnumerable<Pagina> CriarPaginas()
    {
        yield return new Pagina("faturamento-guias","Consultar guias",typeof(ConsultaGuiasViewModel),[F("TermoPaciente", "Paciente (nome ou CPF)", "texto"), F("NumeroGuia", "Nº da guia", "texto"), F("TermoObservacao", "Observação da pendência", "texto"), F("Inicio", "De (atendimento)", "data"), F("Fim", "Até", "data"), F("StatusSelecionado", "Status", "selecao", "Status"), F("ConvenioSelecionado", "Convênio", "selecao", "OpcoesConvenio"), F("ModalidadeSelecionada", "Modalidade", "selecao", "OpcoesModalidade"), F("EspecialidadeSelecionada", "Especialidade", "selecao", "OpcoesEspecialidade")],[],[S("Resultados","Guias encontradas",[T("Resultados","Guias encontradas","Atendimento.Data|Data;Atendimento.Numero|Atend. nº;Atendimento.LancadoPor|Lançou por;Atendimento.Paciente.Nome|Paciente;Atendimento.Paciente.ConvenioNome|Convênio;Atendimento.Modalidade|Modalidade;Especialidade|Especialidade;Tipo|Código;Ordem|Ordem;NumeroGuiaReal|Nº guia;SituacaoGuia|Situação;Glosa|Glosa;ObservacaoPendencia|Observação",[A("Capa", "Capa", Permissao.Nenhuma), A("Historico", "Histórico", Permissao.VerAuditoria, "vm:PodeVerHistorico")])])],[A("Buscar", "Buscar", Permissao.Nenhuma), A("Limpar", "Limpar", Permissao.Nenhuma)], Subtitulo: null, Permissao: Permissao.VerFaturamento, AoAbrir: vm => ((ConsultaGuiasViewModel)vm).CarregarAsync());
        yield return new Pagina("faturamento-pendencias","Pendências de faturamento",typeof(DashboardViewModel),[F("ChipPrimeiros", "1º código", "booleano"), F("ChipSegundos", "2º código", "booleano"), F("ChipAtrasadas", "Atrasadas", "booleano"), F("ChipNoPrazo", "No prazo", "booleano"), F("FiltroTipo", "Código", "selecao", "OpcoesTipo"), F("FiltroModalidade", "Modalidade", "selecao", "OpcoesModalidade"), F("FiltroEspecialidade", "Especialidade", "selecao", "OpcoesEspecialidade"), F("FiltroConvenio", "Convênio", "selecao", "OpcoesConvenio")],["TotalCodigos|Guias em aberto", "CodigosUrgentes|Atrasadas", "TotalPrimeiros|Primeiros códigos", "TotalSegundos|Segundos códigos"],[new Secao("rodada","Rodada de pendências","RodadaBanner",[],[],[],[],Visivel:"RodadaVencida"),new Secao("falha-rodada","Rodada não verificada","RodadaAvisoFalha",[],[],[],[],Visivel:"RodadaIndeterminada"),S("Codigos","Guias e códigos pendentes",[T("Codigos","Guias e códigos pendentes","Selecionada|Seleção;Urgencia|Urgência;PacienteNome|Paciente;PacienteTelefone|Telefone;ConvenioNome|Convênio;Tipo|Código;Ordem|Ordem;DataPrevista|Prevista;DiasEmAtraso|Atraso (dias);FormaObtencao|Como obter;ObservacaoPendencia|Observação",[A("AlternarSelecao", "Selecionar / desmarcar"), A("DarBaixa", "Dar baixa", Permissao.BaixarGuia), A("Whatsapp", "WhatsApp", Permissao.Nenhuma), A("Anotar", "Anotar", Permissao.Nenhuma), A("NaoConformidade", "NC", Permissao.MarcarNaoConformidade, "vm:PodeMarcarNaoConformidade")])]), S("Recursos","Prazos de recurso",[T("Recursos","Prazos de recurso","PacienteNome|Paciente;PacienteTelefone|Telefone;ConvenioNome|Convênio;NumeroGuia|Nº guia;MotivoResumo|Motivo;DataLimiteRecurso|Prazo até;DiasParaFimPrazo|Dias restantes",[new Acao("AbrirGlosas", "Abrir glosas", SemParametro:true)])]), S("Consultas","Consultas a renovar",[T("Consultas","Consultas a renovar","PacienteNome|Paciente;PacienteTelefone|Telefone;ConvenioNome|Convênio;DataVencimento|Vence em;DiasParaVencer|Dias p/ vencer",[A("Renovar", "Renovar", Permissao.LancarAtendimento), A("WhatsappConsulta", "WhatsApp", Permissao.Nenhuma)])])],[A("Atualizar", "Atualizar", Permissao.Nenhuma), A("RodarPendencias", "Rodar pendências", Permissao.Nenhuma), A("LimparFiltros", "Limpar filtros", Permissao.Nenhuma), A("DarBaixaSelecionadas", "Baixa em lote", Permissao.BaixarGuia, "PodeBaixar")], Subtitulo: "ResumoRecorte", Permissao: Permissao.VerFaturamento, AoAbrir: vm => ((DashboardViewModel)vm).CarregarAsync(), Fabrica: sp => CriarDashboard(sp));
        yield return new Pagina("faturamento-faturados","Guias faturadas (baixadas)",typeof(FaturadosViewModel),[F("Inicio", "De", "data"), F("Fim", "Até", "data"), F("FiltroPaciente", "Paciente", "texto"), F("FiltroGuia", "Nº da guia", "texto"), F("FiltroConvenio", "Convênio", "selecao", "ConveniosDoPeriodo")],[],[S("Baixados","Guias faturadas",[T("Baixados","Guias faturadas","Atendimento.Paciente.Nome|Paciente;Atendimento.Paciente.ConvenioNome|Convênio;Tipo|Código;Ordem|Ordem;NumeroGuiaReal|Nº guia;DataBaixa|Baixa;Glosa|Glosa",[A("Capa", "Capa", Permissao.Nenhuma), A("GuiaPdf", "Guia", Permissao.Nenhuma), A("Glosar", "Glosar", Permissao.RegistrarGlosa, "vm:PodeGlosar"), A("Estornar", "Estornar", Permissao.EstornarBaixa, "vm:PodeEstornar")])])],[A("Buscar", "Buscar", Permissao.Nenhuma), A("ExportarCsv", "Exportar CSV", Permissao.Nenhuma), A("LimparFiltro", "Limpar filtro", Permissao.Nenhuma, "FiltroAtivo")], Subtitulo: null, Permissao: Permissao.VerFaturamento, AoAbrir: vm => ((FaturadosViewModel)vm).CarregarAsync());
        yield return new Pagina("faturamento-glosas","Controle de glosas",typeof(GlosasViewModel),[F("FiltroPaciente", "Paciente", "texto"), F("FiltroGuia", "Nº da guia", "texto"), F("SomenteEmAberto", "Mostrar só glosas em aberto", "booleano"), F("SoPrazoVencido", "Só prazo de recurso vencido", "booleano")],[],[S("motivos","O que mais glosa nesta clínica",[T("MotivosRecorrentes","Motivos recorrentes","Rotulo|Motivo;ComoEvitar|Como evitar",[A("AbrirGuiaMotivo","Entenda")])]), S("Glosas","Glosas e recursos",[T("Glosas","Glosas e recursos","Codigo.Atendimento.Paciente.Nome|Paciente;Codigo.Atendimento.Paciente.ConvenioNome|Convênio;Codigo.Tipo|Código;Codigo.NumeroGuiaReal|Nº guia;Codigo.DataGlosa|Glosada em;MotivoAns|Motivo (ANS);Codigo.MotivoGlosa|Complemento;PrazoRotulo|Prazo recurso;Codigo.Glosa|Situação",[A("Reapresentar", "Reapresentar", Permissao.RegistrarGlosa, "vm:PodeRegistrarGlosa"), A("Recuperar", "Recuperada", Permissao.RegistrarGlosa, "vm:PodeRegistrarGlosa")])])],[A("Buscar", "Atualizar", Permissao.Nenhuma), A("GerarRecursoXml", "Recurso de glosa (.xml)", Permissao.RegistrarGlosa, "PodeRegistrarGlosa"), A("AbrirGuia", "Por que as guias são glosadas", Permissao.Nenhuma), A("LimparFiltro", "Limpar filtro", Permissao.Nenhuma, "FiltroAtivo")], Subtitulo: null, Permissao: Permissao.VerFaturamento, AoAbrir: vm => ((GlosasViewModel)vm).CarregarAsync());
        yield return new Pagina("faturamento-nc","Não conformidades (NC)",typeof(NaoConformidadesViewModel),[F("FiltroTexto", "Paciente ou justificativa", "texto")],[],[S("Itens","Não conformidades",[T("Itens","Não conformidades","PacienteNome|Paciente;ConvenioNome|Convênio;Tipo|Código;Ordem|Ordem;DataPrevista|Prevista;Em|Registrada;Justificativa|Justificativa",[A("VerJustificativa", "Ver justificativa", Permissao.Nenhuma), A("Reabrir", "Reabrir", Permissao.MarcarNaoConformidade, "vm:PodeMarcarNaoConformidade")])])],[A("Atualizar", "Atualizar", Permissao.Nenhuma), A("LimparFiltro", "Limpar filtro", Permissao.Nenhuma, "FiltroAtivo")], Subtitulo: null, Permissao: Permissao.VerFaturamento, AoAbrir: vm => ((NaoConformidadesViewModel)vm).CarregarAsync());
        yield return new Pagina("faturamento-relatorios","Relatórios de faturamento",typeof(RelatoriosViewModel),[F("Inicio", "De", "data"), F("Fim", "Até", "data")],["Resumo.TotalCodigos|Guias geradas", "Resumo.Baixados|Baixadas", "Resumo.Pendentes|Pendentes", "Resumo.NaoConformidades|Não conformidades", "Resumo.TaxaBaixa|Taxa de baixa", "Resumo.Glosadas|Glosadas", "Resumo.TaxaGlosa|Taxa de glosa", "Resumo.TempoMedioBaixaDias|Tempo médio de baixa"],[S("PorConvenio","Por convênio",[T("PorConvenio","Por convênio","ConvenioNome|Convênio;TotalCodigos|Gerados;Baixados|Baixados;Pendentes|Pendentes;TaxaBaixa|% baixa;Glosadas|Glosadas;TaxaGlosa|% glosa;TempoMedioBaixaDias|Baixa média (d)",[])]), S("ConsultasEspecialidades","Consultas por especialidade",[T("ConsultasEspecialidades","Consultas por especialidade","Especialidade|Especialidade;Quantidade|Consultas;Baixadas|Baixadas",[])]), S("NaoConformidades","Não conformidades",[T("NaoConformidades","Não conformidades","PacienteNome|Paciente;ConvenioNome|Convênio;Tipo|Tipo;DataPrevista|Prevista;Justificativa|Justificativa;Em|Registrada",[])]), S("Envelhecimento","Envelhecimento das pendências",[T("Envelhecimento","Envelhecimento das pendências","Faixa|Faixa;Quantidade|Qtde",[])]), S("Comparativo","Comparativo mensal",[T("Comparativo","Comparativo mensal","Rotulo|Mês;TotalCodigos|Gerados;Baixados|Baixados;TaxaBaixa|% baixa",[])])],[A("Gerar", "Gerar", Permissao.Nenhuma), A("ExportarCsv", "Exportar CSV", Permissao.Nenhuma), A("GerarFechamento", "Fechamento (PDF)", Permissao.Nenhuma)], Subtitulo: null, Permissao: Permissao.VerIndicadores, AoAbrir: vm => ((RelatoriosViewModel)vm).CarregarAsync());
        yield return new Pagina("faturamento-tiss","Guias TISS — lotes",typeof(TissViewModel),[F("Inicio", "De", "data"), F("Fim", "Até", "data")],[],[S("Lotes","Lotes gerados",[T("Lotes","Lotes gerados","Numero|Nº lote;Operadora|Operadora;DataGeracao|Gerado em;Guias|Guias;StatusRotulo|Situação;DataEnvio|Enviado em;Protocolo|Protocolo;DataRetorno|Retorno em;Glosadas|Glosadas",[A("BaixarXml", "XML", Permissao.Nenhuma), A("MarcarEnviado", "Marcar enviado", Permissao.GerenciarLotesTiss, "vm:PodeGerenciarLotes"), A("RegistrarRetorno", "Registrar retorno", Permissao.GerenciarLotesTiss, "vm:PodeGerenciarLotes")])])],[A("Exportar", "Gerar lote TISS (.xml)", Permissao.GerenciarLotesTiss, "PodeGerenciarLotes"), A("Atualizar", "Atualizar")], Subtitulo: null, Permissao: Permissao.VerFaturamento, AoAbrir: vm => ((TissViewModel)vm).CarregarAsync());
        yield return Parametros();
    }
    private static DashboardViewModel CriarDashboard(IServiceProvider sp)
    {
        var vm=sp.GetRequiredService<DashboardViewModel>();
        vm.AbrirGlosasSolicitado += () => NavegacaoSuite.Ir("faturamento-glosas");
        vm.FichaSolicitada += async id =>
        {
            try
            {
                using var scope=sp.CreateScope();
                var paciente=await scope.ServiceProvider.GetRequiredService<Clinica.Application.Servicos.PacienteService>().ObterAsync(id);
                if(paciente is null)return;
                sp.GetRequiredService<PacienteEmFoco>().Definir(id,paciente.Nome);
                if(!NavegacaoSuite.Ir(ChavesSuite.ConsultorioPaciente))throw new InvalidOperationException("Ficha indisponível nesta sessão.");
            }
            catch(Exception ex){sp.GetRequiredService<Clinica.Desktop.Controls.ISnackbarService>().Erro("Não foi possível abrir a ficha. "+ex.Message);}
        };
        return vm;
    }
}
