using Secao = Clinica.Desktop.Shell.Web.PaginasWebController.Secao;
using Clinica.Desktop.ViewModels;
using Clinica.Domain.Entities;
using static Clinica.Desktop.Shell.Web.PaginasWebController;
namespace Clinica.Faturamento.Web;
public static partial class FaturamentoWebRegistro
{
    private static Pagina Parametros() => new("faturamento-parametros","Configurações do faturamento",typeof(ParametrosViewModel),[],[],[
        S("catalogo","Convênios",[T("Catalogo","Convênios cadastrados","Nome|Nome;Familia|Família;ResumoGuia|Guias;FormatoNumeroGuia|Formato;RegistroAnsOperadora|Registro ANS;Ativo|Ativo",[
            A("EditarConvenio","Configurar",Permissao.ConfigurarFaturamento),A("RemoverConvenio","Excluir",Permissao.ConfigurarFaturamento,"PodeExcluir")])],acoes:[A("NovoConvenio","Adicionar convênio",Permissao.ConfigurarFaturamento),A("AbrirRegrasFamilia","Regras por família",Permissao.ConfigurarFaturamento)]),
        S("modalidades","Modalidades",[T("Modalidades","Modalidades de atendimento","Codigo|Código",[A("RemoverModalidade","Excluir",Permissao.ConfigurarFaturamento,"PodeExcluir")],[
            F("Nome","Nome",permissao:Permissao.ConfigurarFaturamento),new Campo("Base","Comportamento","selecao",Fixas:FontesEnum.ModalidadesBase.Cast<object>().ToArray(),Permissao:Permissao.ConfigurarFaturamento,Guarda:"BaseEditavel"),F("Ativo","Ativa","booleano",permissao:Permissao.ConfigurarFaturamento)])],acoes:[A("NovaModalidade","Adicionar modalidade",Permissao.ConfigurarFaturamento)]),
        S("especialidades","Especialidades",[T("Especialidades","Especialidades de consulta","Codigo|Código",[A("RemoverEspecialidade","Excluir",Permissao.ConfigurarFaturamento,"PodeExcluir")],[F("Nome","Nome",permissao:Permissao.ConfigurarFaturamento),F("Ativo","Ativa","booleano",permissao:Permissao.ConfigurarFaturamento)])],acoes:[A("NovaEspecialidade","Adicionar especialidade",Permissao.ConfigurarFaturamento)]),
        S("tuss","Códigos TUSS",[],campos:[F("TussAcupuntura","Acupuntura",permissao:Permissao.ConfigurarFaturamento),F("TussEletro","Eletroacupuntura",permissao:Permissao.ConfigurarFaturamento),F("TussBsv","BSV",permissao:Permissao.ConfigurarFaturamento),F("TussConsulta","Consulta",permissao:Permissao.ConfigurarFaturamento),F("TussEspecialidade","Consulta de especialidade",permissao:Permissao.ConfigurarFaturamento)]),
        new Secao("clinica","Dados da clínica",null,new[]{("RazaoSocial","Razão social"),("NomeFantasia","Nome fantasia"),("Cnpj","CNPJ"),("Cnes","CNES"),("Endereco","Endereço"),("Telefone","Telefone"),("Email","E-mail"),("ChavePix","Chave Pix"),("Cidade","Cidade"),("CodigoNaOperadora","Código na operadora"),("RegistroAnsOperadora","Registro ANS da operadora")}.Select(x=>F("DadosClinica."+x.Item1,x.Item2,permissao:Permissao.ConfigurarFaturamento)).ToArray(),["DadosClinica.Mensagem|Resultado"],[],[A("DadosClinica.Salvar","Salvar dados da clínica",Permissao.ConfigurarFaturamento)]),
        new Secao("prazos","Prazos e rodada de pendências",null,[F("RegrasFaturamento.JanelaAlertaConsulta","Alerta de consulta (dias)",permissao:Permissao.ConfigurarFaturamento),F("RegrasFaturamento.PrazoRecursoGlosa","Prazo de recurso (dias)",permissao:Permissao.ConfigurarFaturamento),F("RegrasFaturamento.IntervaloRodadaPendencias","Intervalo da rodada (dias)",permissao:Permissao.ConfigurarFaturamento),F("RegrasFaturamento.RodadaAplicaConsultas","Incluir consultas a renovar","booleano",permissao:Permissao.ConfigurarFaturamento),F("RegrasFaturamento.RodadaAplicaCarteirinhas","Incluir carteirinhas a vencer","booleano",permissao:Permissao.ConfigurarFaturamento)],["RegrasFaturamento.Mensagem|Resultado"],[],[A("RegrasFaturamento.SalvarFaturamento","Salvar prazos",Permissao.ConfigurarFaturamento)]),
        new Secao("suporte","Suporte",null,[],["PastaLogs|Pasta dos registros de erro"],[],[A("AbrirPastaLogs","Abrir pasta de registros")])
    ],[A("Salvar","Salvar catálogos e códigos TUSS",Permissao.ConfigurarFaturamento)],Subtitulo:null,Permissao:Permissao.ConfigurarFaturamento,AoAbrir:async o=>{var vm=(ParametrosViewModel)o;await vm.CarregarAsync();await vm.DadosClinica.CarregarAsync();await vm.RegrasFaturamento.CarregarAsync();});
}
