import {type Contexto,type Tabela} from './paginas';
import {CamposReact,AcoesReact} from './paginas-react';
import {HtmlReact} from './html-react';
import {celulaApresentada} from './status-celula';
import {tituloDaTabela} from './layouts';
const normalizar=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const valor=(v:string)=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(v)?`${v.slice(8,10)}/${v.slice(5,7)}/${v.slice(0,4)} ${v.slice(11,16)}`:v;
const prioridade=['horario','datahora','inicioiso','data','databaixa','dataprevista','profissional','contextodalista','status','situacao','situacaoguia','urgencia','numeroguiareal','numeroguia','tipocodigo','convenionome','tipo','proximocontato','proximopasso','responsavel','quantasguias','quando'];
export function usaListaReact(t:Tabela){
 const campos=t.linhas.some(l=>l.campos.some(f=>f.visivel!==false)),acoes=t.linhas.some(l=>l.acoes.some(a=>a.visivel!==false));
 const numericas=t.colunas.filter(col=>['numero','moeda'].includes(col.tipo)||t.linhas.length>0&&t.linhas.every(l=>/^[\d.,% −+–-]+$/.test(l.celulas[col.chave]??''))).length;
 const comparativo=!acoes&&!campos&&numericas>=t.colunas.length-2;
 return t.chave==='Cartoes'||campos||t.chave==='Linhas'||t.colunas.length>=7&&!comparativo;
}
export function usaProfissionaisReact(t:Tabela){return t.chave==='Profissionais'&&t.colunas.some(c=>c.chave==='Ativo')&&t.linhas.every(l=>l.acoes.some(a=>a.chave==='Filtrar'))}
function Celula({tipo,valor:v,contexto:c}:{tipo:string;valor:string;contexto:Contexto}){return <HtmlReact html={celulaApresentada(tipo,valor(v),c.privado)}/>;}
export function ProfissionaisReact({tabela:t,contexto:c}:{tabela:Tabela;contexto:Contexto}){
 return <div className="tabela-web profissionais-filtros" data-tabela-container={t.chave}><HtmlReact html={tituloDaTabela(t,c)}/><div className="profissionais-opcoes" data-testid={`tabela-${t.chave}`}>{t.linhas.length?t.linhas.map(l=>{const ctx={...c,tabela:t.chave,linha:l.id},filtro=l.acoes.find(a=>a.chave==='Filtrar')!,ativo=['true','sim'].includes((l.celulas.Ativo??'').trim().toLowerCase());return <div key={l.id} className={`profissional-filtro ${ativo?'profissional-ativo':''}`} data-linha-id={l.id}><button type="button" className={`botao ${filtro.estilo==='primario'?'primario':'secundario'}`} data-comando={filtro.chave} data-escopo={c.escopo} data-contexto={c.id} data-tabela={t.chave} data-linha={l.id} aria-pressed={ativo} aria-label={`${filtro.rotulo}: ${l.celulas.Nome??''}`} disabled={c.ocupado||filtro.habilitada===false} hidden={filtro.visivel===false}><strong data-coluna="Nome">{l.celulas.Nome??''}</strong><span data-coluna="Quantidade">{l.celulas.Quantidade??''} horários</span><small data-coluna="Ativo">{ativo?'Filtro ativo':'Ver agenda'}</small></button>{t.colunas.filter(col=>!['Nome','Quantidade','Ativo'].includes(col.chave)).map(col=><span key={col.chave} data-coluna={col.chave}>{col.rotulo}: <Celula tipo={col.tipo} valor={l.celulas[col.chave]??''} contexto={c}/></span>)}<CamposReact campos={l.campos} contexto={ctx}/><AcoesReact acoes={l.acoes.filter(a=>a!==filtro)} contexto={ctx}/></div>}):<p className="vazio">{t.vazio}</p>}</div></div>;
}
export function ListaReact({tabela:t,contexto:c}:{tabela:Tabela;contexto:Contexto}){
 const identidade=t.colunas.find(col=>normalizar(col.rotulo)==='paciente'||['pacientenome','nomepaciente','paciente'].includes(normalizar(col.chave))||normalizar(col.chave).endsWith('pacientenome'))??t.colunas.find(col=>normalizar(col.chave)==='nome')??t.colunas[0];
 const modalidade=t.chave==='Cartoes',restantes=t.colunas.filter(col=>col!==identidade),preferidas=restantes.filter(col=>prioridade.includes(normalizar(col.chave.split('.').at(-1)??col.chave))),principais=[...preferidas,...restantes.filter(col=>!preferidas.includes(col))].slice(0,modalidade?3:4),detalhes=restantes.filter(col=>!principais.includes(col));
 return <div className={`tabela-web lista-responsiva ${modalidade?'modalidades-lista':'lista-compacta'}`} data-tabela-container={t.chave}><HtmlReact html={tituloDaTabela(t,c)}/><div className="registros-cartoes" data-testid={`tabela-${t.chave}`}>{t.linhas.length?t.linhas.map(l=>{const ctx={...c,tabela:t.chave,linha:l.id},temCampos=l.campos.some(f=>f.visivel!==false);const definicao=(cols:typeof t.colunas)=>cols.map(col=><div key={col.chave} data-coluna={col.chave}><dt>{col.rotulo}</dt><dd><Celula tipo={col.tipo} valor={l.celulas[col.chave]??''} contexto={c}/></dd></div>);return <article key={l.id} className={`registro-cartao ${l.selecionada?'linha-selecionada':''}`} data-linha-id={l.id}><div className="registro-conteudo"><h4 data-coluna={identidade?.chave}><Celula tipo={identidade?.tipo??'texto'} valor={l.celulas[identidade?.chave]??'Registro'} contexto={c}/></h4><dl className="registro-resumo">{definicao(principais)}</dl>{(detalhes.length>0||temCampos)&&<details className="registro-detalhes" data-preservar={`${c.escopo}:${c.id}:${t.chave}:${l.id}`}><summary>{temCampos?'Abrir detalhes e preenchimento':'Ver detalhes'}</summary>{detalhes.length>0&&<dl>{definicao(detalhes)}</dl>}<CamposReact campos={l.campos} contexto={ctx}/></details>}</div><div className="acoes-na-linha"><AcoesReact acoes={l.acoes} contexto={ctx}/></div></article>}):<div className="vazio"><strong>{t.vazio}</strong></div>}</div></div>;
}
