export type Aula={id:string;titulo:string;descricao:string;categoria:string;duracaoTexto:string;duracao:number;posicao:number;concluida:boolean;estado:string;capitulos:{inicio:number;titulo:string;texto:string}[]};
export type Catalogo={aulas:Aula[];categorias:string[];resumo:string};
const h=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let filtro='',categoria='',situacao='todas';
export function treinamento(c?:Catalogo,a?:Aula,url?:string){
 if(!c)return '<div class="mensagem-web">Carregando treinamento…</div>';
 const aulas=c.aulas.filter(a=>(!filtro||(a.titulo+' '+a.descricao).toLocaleLowerCase('pt-BR').includes(filtro.toLocaleLowerCase('pt-BR')))&&(!categoria||categoria==='Todas as categorias'||a.categoria===categoria)&&(situacao==='todas'||a.concluida===(situacao==='concluidas')));
 return `<div class="pagina-web"><header class="cabecalho-pagina"><div><h1>Treinamento</h1><p>${h(c.resumo)}</p></div><button class="botao" data-sair-treinamento>Voltar à tela</button></header><div class="campos-web"><label class="campo-web">Buscar aula<input id="busca-aula" value="${h(filtro)}" type="search"/></label><label class="campo-web">Categoria<select id="categoria-aula">${c.categorias.map(v=>`<option ${v===categoria?'selected':''}>${h(v)}</option>`).join('')}</select></label><label class="campo-web">Progresso<select id="situacao-aula">${[['todas','Todas'],['pendentes','Pendentes'],['concluidas','Concluídas']].map(([v,t])=>`<option value="${v}" ${v===situacao?'selected':''}>${t}</option>`).join('')}</select></label></div>${a&&url?`<section class="secao-web aula-aberta"><h2>${h(a.titulo)}</h2><p>${h(a.descricao)}</p><video id="video-aula" controls preload="metadata" src="${h(url)}" data-aula-id="${h(a.id)}" data-posicao="${a.posicao}"></video><div class="acoes-web"><button class="botao" data-aula-reiniciar="${h(a.id)}">Assistir desde o início</button><button class="botao primario" data-aula-concluir="${h(a.id)}">Marcar como concluída</button></div><div class="capitulos-aula">${a.capitulos.map(p=>`<button class="botao" data-capitulo="${p.inicio}">${h(p.titulo)}</button><p>${h(p.texto)}</p>`).join('')}</div></section>`:''}<div class="catalogo-aulas">${aulas.map(a=>`<article class="secao-web"><small>${h(a.categoria)} · ${h(a.duracaoTexto)}</small><h2>${h(a.titulo)}</h2><p>${h(a.descricao)}</p><progress max="${a.duracao||1}" value="${a.concluida?a.duracao:a.posicao}" aria-label="Progresso da aula"></progress><button class="botao ${a.concluida?'':'primario'}" data-aula="${h(a.id)}">${h(a.estado)}</button></article>`).join('')}</div>${aulas.length?'':'<p class="mensagem-web">Nenhuma aula corresponde aos filtros.</p>'}</div>`;
}
export function filtroTreinamento(el:HTMLInputElement){if(el.id==='busca-aula')filtro=el.value;else if(el.id==='categoria-aula')categoria=el.value;else if(el.id==='situacao-aula')situacao=el.value;else return false;return true}
export function prepararVideo(enviar:(acao:string,chave:string,valor?:unknown)=>void){const v=document.querySelector<HTMLVideoElement>('#video-aula');if(!v||v.dataset.ligado)return;v.dataset.ligado='true';let salvo=0;v.onloadedmetadata=()=>{v.currentTime=Math.min(Number(v.dataset.posicao)||0,v.duration||0)};const gravar=(concluida=false)=>{if(!Number.isFinite(v.currentTime))return;enviar('progresso-aula',v.dataset.aulaId!,{posicao:v.currentTime,concluida})};v.onpause=()=>{if(v.dataset.movendo!=='true')gravar()};v.onended=()=>gravar(true);v.ontimeupdate=()=>{if(Math.abs(v.currentTime-salvo)>10){salvo=v.currentTime;gravar()}}}
